version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot
    versions:
    - 2.4.3
    - 2.4.4
    - 2.4.5
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.3
    - 2.4.4
    - 2.4.5
  - dependency-name: org.springframework.boot:spring-boot-starter-data-jpa
    versions:
    - 2.4.3
    - 2.4.4
    - 2.4.5
  - dependency-name: net.serenity-bdd:serenity-single-page-report
    versions:
    - 2.3.13
    - 2.4.1
    - 2.4.2
    - 2.4.4
    - 2.4.5
  - dependency-name: org.springframework.boot:spring-boot-starter-web
    versions:
    - 2.4.3
    - 2.4.4
    - 2.4.5
  - dependency-name: org.springframework.boot:spring-boot-configuration-processor
    versions:
    - 2.4.3
    - 2.4.4
    - 2.4.5
  - dependency-name: org.springframework.boot:spring-boot-autoconfigure
    versions:
    - 2.4.3
    - 2.4.4
    - 2.4.5
  - dependency-name: org.springframework.boot:spring-boot-actuator
    versions:
    - 2.4.3
    - 2.4.4
    - 2.4.5
  - dependency-name: org.springframework.boot:spring-boot-starter-batch
    versions:
    - 2.4.3
    - 2.4.4
    - 2.4.5
  - dependency-name: org.springframework.boot:spring-boot-starter-test
    versions:
    - 2.4.3
    - 2.4.4
    - 2.4.5
  - dependency-name: net.serenity-bdd:serenity-gradle-plugin
    versions:
    - 2.3.13
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-validation
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
    - 2.4.5
  - dependency-name: au.com.dius.pact
    versions:
    - 4.1.16
    - 4.2.0
    - 4.2.1
    - 4.2.2
    - 4.2.3
    - 4.2.4
  - dependency-name: com.github.ben-manes.versions
    versions:
    - 0.38.0
  - dependency-name: com.zaxxer:HikariCP
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: info.solidsoft.pitest
    versions:
    - 1.6.0
  - dependency-name: org.liquibase:liquibase-core
    versions:
    - 4.3.1
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.1
  - dependency-name: uk.gov.hmcts.reform:service-auth-provider-client
    versions:
    - 4.0.0
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.1
  - dependency-name: org.apache.tomcat.embed:tomcat-embed-core
    versions:
    - 10.0.2
  - dependency-name: uk.gov.hmcts.reform:idam-client
    versions:
    - 2.0.0
  - dependency-name: org.springframework.cloud:spring-cloud-openfeign
    versions:
    - 3.0.1
