name: rpa-native-pdf-annotator-app
home: https://github.com/hmcts/rpa-native-pdf-annotator-app
version: 0.0.1 # WHAT SHOULD THIS BE
description: Helm chart for the HMCTS Native PDF Annotator API
maintainers:
  - name: HMCTS EM Team
    email: pawel.kaczmarek@hmcts.net
