
# settings used for functional tests
idam:
  s2s-auth:
    url: ${S2S_BASE_URI:http://localhost:4502}
    totp_secret: ${FUNCTIONAL_TEST_CLIENT_S2S_TOKEN:AAAAAAAAAAAAAAAA}
    microservice: em_gw
  api:
    url: ${IDAM_API_BASE_URI:http://localhost:4501}
  client:
    id: webshow
    secret: ${FUNCTIONAL_TEST_CLIENT_OAUTH_SECRET:AAAAAAAAAAAAAAAA}
    redirect_uri: ${IDAM_WEBSHOW_WHITELIST:http://localhost:8080/oauth2redirect}

spring:
  database:
    driverClassName: org.h2.Driver
  datasource:
    url: jdbc:h2:mem:test_mem
    #    url: jdbc:h2:./build/h2_db/test;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: true

azure:
  app_insights_key: ${APPINSIGHTS_INSTRUMENTATIONKEY:false}
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:dummy}
