
# settings used for functional tests
idam:
  s2s-auth:
    url: ${S2S_BASE_URI:http://localhost:4502}
    totp_secret: ${FUNCTIONAL_TEST_CLIENT_S2S_TOKEN:AAAAAAAAAAAAAAAA}
    microservice: em_gw
  api:
    url: ${IDAM_API_BASE_URI:http://localhost:4501}
  client:
    id: webshow
    secret: ${FUNCTIONAL_TEST_CLIENT_OAUTH_SECRET:AAAAAAAAAAAAAAAA}
    redirect_uri: ${IDAM_WEBSHOW_WHITELIST:http://localhost:8080/oauth2redirect}
