apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SERVICE_NAME}-config
  namespace: ${NAMESPACE}
data:
  IDAM_API_BASE_URI: "https://preprod-idamapi.reform.hmcts.net:3511"
  S2S_BASE_URI: "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
  DM_STORE_APP_BASE_URI: "http://dm-store-aat.service.core-compute-aat.internal"
  EM_ANNO_APP_BASE_URI: "http://em-anno-aat.service.core-compute-aat.internal"