---
spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${OPEN_ID_API_BASE_URI:http://localhost:5000/o}
        registration:
          oidc:
            client-id: webshow
            client-secret: ${S2S_KEY:AAAAAAAAAAAAAAAA}

test:
  url: ${TEST_URL:http://localhost:8080}

idam:
  api:
    url: ${IDAM_API_BASE_URI:http://localhost:5000}
  client:
    id: ${OAUTH_CLIENT:webshow}
    secret: ${FUNCTIONAL_TEST_CLIENT_OAUTH_SECRET:AAAAAAAAAAAAAAAA}
    redirect_uri: ${IDAM_WEBSHOW_WHITELIST:http://localhost:8080/oauth2redirect}
    grant_type: 'password'
    scope: 'openid roles profile'

s2s:
  api:
    url: ${S2S_BASE_URI:http://localhost:4502}
    secret: ${FUNCTIONAL_TEST_CLIENT_S2S_TOKEN:AAAAAAAAAAAAAAAA}
    serviceName: ${S2S_SERVICE_NAME:em_gw}
    ccdGwSecret: ${FUNCTIONAL_TEST_CCD_GW_SERVICE_SECRET:AAAAAAAAAAAAAAAA}
    ccdGwServiceName: ${CCD_GW_SERVICE_NAME:ccd_gw}


ccd-def:
  api:
    url: 'http://localhost:4451'

document_management:
  url: ${DM_STORE_APP_URL:http://localhost:4603}

core_case_data:
  api:
    url: 'http://localhost:4452'


annotation:
  api:
    url: ${EM_ANNO_APP_URL:http://localhost:4623}

oidc:
  issuer: ${OIDC_ISSUER_BASE_URI:http://localhost:8080/openam/oauth2/hmcts}

toggle:
  enable_document_task_endpoint: ${ENABLE_DOCUMENT_TASK_ENDPOINT:false}