apiVersion: v2
name: em-npa
home: https://github.com/hmcts/em-native-pdf-annotator-app
version: 1.0.20
description: Helm chart for HMCTS Native PDF Annotator API
maintainers:
  - name: HMCTS EM Team
dependencies:
  - name: java
    version: 4.1.0
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
