apiVersion: v2
name: em-npa
home: https://github.com/hmcts/em-native-pdf-annotator-app
version: 2.0.2
description: Helm chart for HMCTS Native PDF Annotator API
maintainers:
  - name: HMCTS EM Team
dependencies:
  - name: java
    version: 4.1.0
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
  - name: xui-webapp
    version: ~1.0.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: xui-webapp.enabled
  - name: idam-pr
    version: ~2.3.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: idam-pr.enabled
