java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    SHOW_SQL: true
    LOGGING_LEVEL_ORG_HIBERNATE_SQL: DEBUG
    SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
    LOGGING_LEVEL_ORG_HIBERNATE_ORM_JDBC_BIND: TRACE
    S2S_NAMES_DELETE_WHITELIST: dm_store,em_gw
    ENABLE_DELETE_ENDPOINT: true
