java:
  postgresql:
    postgresqlUsername: emnpa
    postgresqlPassword: emnpa
    nameOverride: rpa-npa-db
  image: 'hmctspublic.azurecr.io/em/npa:latest'
  applicationPort: 8080
  ingressHost: em-npa-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: em
  keyVaults:
    em-npa:
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: APPINSIGHTS_INSTRUMENTATIONKEY
        - name: microservicekey-em-npa-app
          alias: S2S_KEY
        - name: npa-POSTGRES-PASS
          alias: SPRING_DATASOURCE_PASSWORD
  environment:
    RUN_DB_MIGRATION_ON_STARTUP: 'false'
    IDAM_API_BASE_URI: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    OPEN_ID_API_BASE_URI: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/o
    OIDC_ISSUER_BASE_URI: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
    S2S_BASE_URI: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    DM_STORE_APP_URL: http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    EM_ANNO_APP_URL: http://em-anno-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CDAM_URL: http://ccd-case-document-am-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal

    SPRING_DATASOURCE_USERNAME: annotation@em-npa-postgres-db-{{ .Values.global.environment }}
    SPRING_DATASOURCE_URL: jdbc:postgresql://em-npa-postgres-db-{{ .Values.global.environment }}.postgres.database.azure.com:5432/annotation?sslmode=require
    TEST_VAR_1: test1
    TEST_VAR_2: test2

    ENABLE_DB_MIGRATE: false
    JSON_CONSOLE_PRETTY_PRINT: false
    LOG_OUTPUT: single
    ROOT_LOGGING_LEVEL: INFO
    LOG_LEVEL_SPRING_WEB: INFO
    LOG_LEVEL_DM: INFO
    SHOW_SQL: false
    ENDPOINTS_HEALTH_SENSITIVE: false
    ENDPOINTS_INFO_SENSITIVE: false
    ENABLE_IDAM_HEALTH_CHECK: false
    ENABLE_S2S_HEALTH_CHECK: false
    ENABLE_LIQUIBASE: false
    ENABLE_DOCUMENT_TASK_ENDPOINT: false
    SERVER_PORT: 8080
